### ISSUE TITLE
unable to include in polymer 3.0 (litelement)

### ISSUE THREAD

**Issue by Pankraz76** [LostInBrittany/granite-bootstrap#9]
Hi,
i´m trying to include the boostrap styling into my local element styling unfortunately without success. The import is working I´ve already checked it, but the inclusion somehow not.

Would you please check my case and give me support:
![image](https://user-images.githubusercontent.com/8830888/44140801-7ec642ae-a07b-11e8-85ca-4c8fed1b64f0.png)

**Comment by LostInBrittany** [comment]
Oups, sorry about that, the README was a bit outdated, the using instructions weren't right.
I have updated the README, so now it should work if you follow the steps:


#### 1. Install `granite-bootstrap`


Install the component using [npm](https://www.npmjs.com/):

```sh
$ npm i @granite-elements/granite-bootstrap --save
```


#### 2. Import the *granite-bootstrap* module you want to use


Once installed, import it in your application. Usually you will simply want to import `granite-bootstrap.js` (wrap around `bootstrap.css`) or `granite-bootstrap-min.js` (wrap around `bootstrap.min.css`).

Supossing you want to import `granite-bootstrap.js`:
 
```
import '@granite-elements/granite-bootstrap/granite-bootstrap.js';
``` 

#### 3. Inside your component, use *granite-bootstrap* as shared style

In your element's template you add the include for the *granite-bootstrap* module:

```
<style include="granite-bootstrap"></style>
```
 

#### A complete example

```
<!-- import the module  -->
 <script type="module">
    import '@granite-elements/granite-bootstrap/granite-bootstrap.js';
</script>
<dom-module id="x-foo">
  <template>
    <!-- include the style module by name -->
    <style include="granite-bootstrap"></style>
    <style>:host { display: block; }</style>
    Hi
  </template>
  <script>Polymer({is: 'x-foo'});</script>
</dom-module>
```

**Comment by Pankraz76** [comment]
@LostInBrittany sorry still not working: what am i doing wrong?
![image](https://user-images.githubusercontent.com/8830888/44197561-3f313080-a13f-11e8-895d-252ec405ee02.png)

**Comment by LostInBrittany** [comment]
Oh, looking at your screencap it should work.
In the browser dev tools, do you see the `granite-bootstrap.js` being loaded?

There is maybe another problem... I see you're creating a LitElement based element and not a Polymer based one. I am not sure if Polymer shared styles are implemented on LitElement, I'm going to try and I tell you...

**Comment by Pankraz76** [comment]
yep the js file gets loaded, thank you

**Comment by icolquemamani** [comment]
> Oh, mirando tu captura de pantalla debería funcionar. 
> En las herramientas de desarrollo del navegador, ¿ves la `granite-bootstrap.js`carga?
> 
> Quizás haya otro problema ... veo que estás creando un elemento basado en LitElement y no uno basado en Polymer. No estoy seguro de si los estilos compartidos de Polymer se implementan en LitElement, lo intentaré y le diré ...

Tengo el mismo problema, tiene alguna solución?
